export const colors = {
    BLUE_ACCENT_COLOR: "#54B9D1",
    GREEN_ACCENT_COLOR: "#58BE3F",
    WRONG_COLOR: "#F27C83",
    SOFT_GRAY_COLOR: "#F3F4F6",
    MEDIUM_GRAY_COLOR: "#AAB2BD",
    HARD_GRAY_COLOR: "#434A53",
    BG_COLOR_WHITE: "#FFFFFF",
    VK_BTN_COLOR: "#3375F6",
    EMAIL_LOGIN_BORDER_COLOR: "#CCD1D9",
    APPLE_AUTH_COLOR: "#252526"
}
